server:
  port: ${A6_PROJECTS_CORE_PORT:10200}

spring:
  config:
    import: classpath:/api.yml, classpath:/security.yml, classpath:/amqp.yml
  application:
    name: ${A6_PROJECTS_CORE_APP_NAME:projects.core}
  data:
    mongodb:
      uri: ${A6_PROJECTS_CORE_MONGO_DB_URI:mongodb://localhost:27017/}${A6_PROJECTS_CORE_MONGO_DB_NAME:a6-projects-core}${A6_PROJECTS_CORE_MONGO_DB_PARAMS:?}
