server:
  port: ${PORT:8090}

spring:
  application:
    name: ${APP_NAME:projects.core}
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/projects.core}
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://127.0.0.1:8761/eureka/}
    healthcheck:
      enabled: true
