context:
  initializer:
    classes: com.angorasix.projects.core.BeansInitializer
server:
  port: ${A6_PROJECTS_CORE_PORT:9082}

spring:
  config:
    import: classpath:/api.yml, classpath:/security.yml
  application:
    name: ${A6_PROJECTS_CORE_APP_NAME:projects.core}
  data:
    mongodb:
      uri: ${A6_PROJECTS_CORE_MONGO_DB_URI:mongodb://localhost:27017/}${A6_PROJECTS_CORE_MONGO_DB_NAME:a6-contributors}${A6_PROJECTS_CORE_MONGO_DB_PARAMS:?}
