context:
  initializer:
    classes: com.angorasix.projects.core.BeansInitializer
server:
  port: ${PORT:8090}

spring:
  application:
    name: ${APP_NAME:projects.core}
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/projects.core}
