context:
  initializer:
    classes: com.angorasix.projects.core.BeansInitializer
server:
  port: ${PORT:9082}

spring:
  application:
    name: ${APP_NAME:projects.core}
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/projects.core}

configs:
  api:
    contributorHeader: ${A6_PROJECTS_CORE_CONTRIBUTORHEADER:A6-Contributor}
